version: '3'

services:
  untrusted:
    image: sebreiro/untrusted_js_game:alpine-1.0
    container_name: untrusted_js_game
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge