# Build
FROM ubuntu:16.04 as builder

WORKDIR /source

RUN set -ex && \
    apt-get update -y && \
    apt-get install -y git make default-jre && \
    git clone https://github.com/Sebreiro/untrusted . && \
    chmod +x deploy.sh && \
    make deploy-full

# Deploy
FROM nginx:1.17.0-alpine

WORKDIR /usr/share/nginx/html

COPY --from=builder /source/untrusted_site .